### ISSUE TITLE
How to use the software to process local images?

### ISSUE THREAD

**Issue by zutyhcx** [rtorii/Mask-Removal#1]
I never appreciate a person who is wearing a face mask. I dream of a software that can remove a face mask from a photograph. I finally found it today and tried it. Though it can't calculate the real face of a person who is wearing a face mask, it still works really well. But I found it can only process the video from a camera. I have many pictures of people wearing face masks on my phone. So I can only use a virtual camera such as OBS. I want to know how to batch process local images using software.

The farthest distance in the world is not the end of the earth, but when I stand in front of you, I can't see your face. I hope there will be no masks on the campus in the future, only a smile.

**Comment by rtorii** [comment]
In the repository, I have uploaded a file called applocal.py (a modified version of app.py) that processes pictures in a folder called 'photos' and saves the processed pictures in another folder called 'output_photos'.

If you save all pictures in the 'photos' folder and run applocal.py, the program should save all processed pictures in the 'output_photos' folder.

It is working fine on my computer so I hope it works fine on yours too.

**Comment by zutyhcx** [comment]
Thanks very much!
